console.log("hi");
console.log("hi");
console.log("hi");
console.log("hi");
console.log("hi");
console.log("hi");
console.log("tag");
console.log("tag");
console.log("tag");
console.log("tag");
console.log("This is master");